name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Release Electron App
    runs-on: ${{ matrix.os }}
    # 添加权限设置，确保有足够权限创建release和上传文件
    permissions:
      contents: write
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Build Electron App
        run: npm run build:all

        shell: bash
      # - name: Changelog
      #   uses: scottbrenner/generate-changelog-action@master
      #   id: Changelog
      #   env:
      #     REPO: ${{ github.repository }}

      # - name: Prepare Release Notes
      #   id: release_notes
      #   run: |
      #     echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
      #     echo "## Electron Quasar Demo ${{ github.ref_name }}" >> $GITHUB_ENV
      #     echo "" >> $GITHUB_ENV
      #     echo "### 更新内容" >> $GITHUB_ENV
      #     echo "- 自动构建发布版本 ${{ github.ref_name }}" >> $GITHUB_ENV
      #     echo "- 包含Windows和macOS安装包" >> $GITHUB_ENV
      #     echo "EOF" >> $GITHUB_ENV
      #   shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/electron/**/*.exe
            dist/electron/**/*.AppImage
            dist/electron/**/*.dmg
            dist/electron/**/*.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
